name: optimove_flutter
version: 3.3.0
description: Optimove Flutter SDK
homepage: https://www.optimove.com/
repository: https://github.com/optimove-tech/Optimove-SDK-Flutter/

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.optimove.flutter
        pluginClass: OptimoveFlutterPlugin
      ios:
        pluginClass: OptimoveFlutterPlugin